### ISSUE TITLE
pip install pyrtt-viewer fails

### ISSUE THREAD

**Issue by spachner** [thomasstenersen/pyrtt-viewer#4]
Hi,

thanks for providings the rtt viewer, unfortunately installation fails

```
[ spachner@MacBookPro ] ~
$ pip search pyrtt
pyrtt-viewer (0.1.1)  - A simple script for RTT I/O
[ spachner@MacBookPro ] ~
$ pip install pyrtt-viewer
Collecting pyrtt-viewer
  Could not find a version that satisfies the requirement pyrtt-viewer (from versions: )
No matching distribution found for pyrtt-viewer
```

Any hints?
regards

spachner

**Comment by spachner** [comment]
Hi, 

thanks for your reply. Your are right, I tried pip from version 2. pip3 worked.

regards

spachner

**Comment by thomasstenersen** [comment]
Glad to hear it's working :) Btw, I would recommend using `virtualenv` to have clean separations between python installs and projects.

-Thomas
